// Generated by gencpp from file thorvald_2d_nav/GpsSwitch.msg
// DO NOT EDIT!


#ifndef THORVALD_2D_NAV_MESSAGE_GPSSWITCH_H
#define THORVALD_2D_NAV_MESSAGE_GPSSWITCH_H

#include <ros/service_traits.h>


#include <thorvald_2d_nav/GpsSwitchRequest.h>
#include <thorvald_2d_nav/GpsSwitchResponse.h>


namespace thorvald_2d_nav
{

struct GpsSwitch
{

typedef GpsSwitchRequest Request;
typedef GpsSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GpsSwitch
} // namespace thorvald_2d_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thorvald_2d_nav::GpsSwitch > {
  static const char* value()
  {
    return "2e3c0c75e8b47d5932d7a16eda636d7b";
  }

  static const char* value(const ::thorvald_2d_nav::GpsSwitch&) { return value(); }
};

template<>
struct DataType< ::thorvald_2d_nav::GpsSwitch > {
  static const char* value()
  {
    return "thorvald_2d_nav/GpsSwitch";
  }

  static const char* value(const ::thorvald_2d_nav::GpsSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::thorvald_2d_nav::GpsSwitchRequest> should match 
// service_traits::MD5Sum< ::thorvald_2d_nav::GpsSwitch > 
template<>
struct MD5Sum< ::thorvald_2d_nav::GpsSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thorvald_2d_nav::GpsSwitch >::value();
  }
  static const char* value(const ::thorvald_2d_nav::GpsSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thorvald_2d_nav::GpsSwitchRequest> should match 
// service_traits::DataType< ::thorvald_2d_nav::GpsSwitch > 
template<>
struct DataType< ::thorvald_2d_nav::GpsSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::thorvald_2d_nav::GpsSwitch >::value();
  }
  static const char* value(const ::thorvald_2d_nav::GpsSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thorvald_2d_nav::GpsSwitchResponse> should match 
// service_traits::MD5Sum< ::thorvald_2d_nav::GpsSwitch > 
template<>
struct MD5Sum< ::thorvald_2d_nav::GpsSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thorvald_2d_nav::GpsSwitch >::value();
  }
  static const char* value(const ::thorvald_2d_nav::GpsSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thorvald_2d_nav::GpsSwitchResponse> should match 
// service_traits::DataType< ::thorvald_2d_nav::GpsSwitch > 
template<>
struct DataType< ::thorvald_2d_nav::GpsSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::thorvald_2d_nav::GpsSwitch >::value();
  }
  static const char* value(const ::thorvald_2d_nav::GpsSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THORVALD_2D_NAV_MESSAGE_GPSSWITCH_H
