// Generated by gencpp from file thorvald_2d_nav/sub_goal.msg
// DO NOT EDIT!


#ifndef THORVALD_2D_NAV_MESSAGE_SUB_GOAL_H
#define THORVALD_2D_NAV_MESSAGE_SUB_GOAL_H

#include <ros/service_traits.h>


#include <thorvald_2d_nav/sub_goalRequest.h>
#include <thorvald_2d_nav/sub_goalResponse.h>


namespace thorvald_2d_nav
{

struct sub_goal
{

typedef sub_goalRequest Request;
typedef sub_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sub_goal
} // namespace thorvald_2d_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thorvald_2d_nav::sub_goal > {
  static const char* value()
  {
    return "bf8fa84d852a8768a882827724d718cf";
  }

  static const char* value(const ::thorvald_2d_nav::sub_goal&) { return value(); }
};

template<>
struct DataType< ::thorvald_2d_nav::sub_goal > {
  static const char* value()
  {
    return "thorvald_2d_nav/sub_goal";
  }

  static const char* value(const ::thorvald_2d_nav::sub_goal&) { return value(); }
};


// service_traits::MD5Sum< ::thorvald_2d_nav::sub_goalRequest> should match 
// service_traits::MD5Sum< ::thorvald_2d_nav::sub_goal > 
template<>
struct MD5Sum< ::thorvald_2d_nav::sub_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thorvald_2d_nav::sub_goal >::value();
  }
  static const char* value(const ::thorvald_2d_nav::sub_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thorvald_2d_nav::sub_goalRequest> should match 
// service_traits::DataType< ::thorvald_2d_nav::sub_goal > 
template<>
struct DataType< ::thorvald_2d_nav::sub_goalRequest>
{
  static const char* value()
  {
    return DataType< ::thorvald_2d_nav::sub_goal >::value();
  }
  static const char* value(const ::thorvald_2d_nav::sub_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thorvald_2d_nav::sub_goalResponse> should match 
// service_traits::MD5Sum< ::thorvald_2d_nav::sub_goal > 
template<>
struct MD5Sum< ::thorvald_2d_nav::sub_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thorvald_2d_nav::sub_goal >::value();
  }
  static const char* value(const ::thorvald_2d_nav::sub_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thorvald_2d_nav::sub_goalResponse> should match 
// service_traits::DataType< ::thorvald_2d_nav::sub_goal > 
template<>
struct DataType< ::thorvald_2d_nav::sub_goalResponse>
{
  static const char* value()
  {
    return DataType< ::thorvald_2d_nav::sub_goal >::value();
  }
  static const char* value(const ::thorvald_2d_nav::sub_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THORVALD_2D_NAV_MESSAGE_SUB_GOAL_H
