DWAPlannerROS:
  #default 2.5 -> with this value the robot sometimes gets to close to the wall when leaving a goal position in narrow corridors, causing dwa planner to have problems
  acc_lim_x: 1.0
  
  acc_lim_y: 0.0
  
  #default 3.2
  acc_lim_th: 0.4

  max_vel_x: 0.2
  min_vel_x: 0.0  
  min_vel_y: 0.0
  max_vel_y: 0.0
  max_rot_vel: 0.4
  min_rot_vel: 0.1

  yaw_goal_tolerance: 0.5
  
  #default:0.1 -> with this value the robot sometimes has troubles achieving the goal, due to low tolerance
  xy_goal_tolerance: 0.5
  
  
  # if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.
  latch_xy_goal_tolerance: true
 

  sim_time: 2.1
  

#cost =  path_distance_bias * (distance to path from the endpoint of the trajectory in meters)  + goal_distance_bias * (distance to local goal from the endpoint of the trajectory in meters)  + occdist_scale * (maximum obstacle cost along the trajectory in obstacle cost (0-254))
  path_distance_bias: 32.0 #default:32, previous:5
  goal_distance_bias: 24.0 #default:24, previous:9
  occdist_scale: 0.01 #default:0.01

  
  oscillation_reset_dist: 0.05


  prune_plan: true

  holonomic_robot: false

